### PR TITLE
contrast-releases: add mysql demo and runtime.yml for metal platforms

### PR DESCRIPTION
**Pull request by katexochen**
We now have both demos in deployment, we'll have to see if that fits our needs.

### CODE REVIEW

**Review by msanft — APPROVED** [review]
Demo and runtime artifacts exist on the release, so LGTM.

**Comment by katexochen** [comment]
> test release: https://github.com/edgelesssys/contrast/actions/runs/12547976345

Ah, we can't test this as it uses the script from main.

**Comment by edgelessci** [comment]
Successfully created backport PR for `release/v1.2`:
- #1111

**Comment by katexochen** [comment]
Looks like it works as intended: https://github.com/edgelesssys/contrast/pull/1108/commits/8fdacf1ccc7b866bba7ce777b53858e82c95b1fd

**Pull request merged**
