### PR TITLE
docs: animated banner

### PR DESCRIPTION
**Pull request by laralaske**

### CODE REVIEW

**Comment by katexochen** [comment]
Do we want to keep the old version?

**Comment by laralaske** [comment]
> Do we want to keep the old version? It's not referenced anywhere now.

ah no, deleted

**Comment by katexochen** [comment]
@laralaske could you sign the cla?

**Comment by laralaske** [comment]
> @laralaske could you sign the cla?

Sorry! Yes, done

**Review by katexochen — APPROVED** [review]

**Pull request merged**
