### PR TITLE
e2e: show debug logs on error

### PR DESCRIPTION
**Pull request by burgerdev**

### CODE REVIEW

**Comment by katexochen** [comment]
When will this show? Aren't we normally dropping stdout?

**Comment by katexochen** [comment]
Okay, but shouldn't we also see logs for set/verify? https://github.com/edgelesssys/contrast/actions/runs/11890697328/job/33134201064?pr=1009#step:11:252

**Comment by burgerdev** [comment]
Those did not fail - the one instance I linked is an expected failure during the recovery test.

**Comment by katexochen** [comment]
Makes sense, thanks!

**Pull request merged**
